#!/usr/bin/env zsh

local arg="$1"

case "$arg" in
    install|info|adopt|add)
        shift
        __zshero::core::run_command \
            "$arg" \
            "$argv[@]"
        ;;
    "")
        __zshero::core::run_command "info"
        ;;

    *)
        __zshero::io::print::put "Some arguments"
        # __zplug::core::arguments::exec "$argv[@]"
        ;;
esac

return $status
